name: Update Weather

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7,12,16 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
            pip install pipenv
            pipenv install
      - name: Update Weather
        run: |
          ./update_github_readme.sh
          git config --global user.email "jackie.yt.wang@gmail.com"
          git config --global user.name "Jackie Wang"
          git add README.md
          git commit -m "Update weather"
          git push origin main
