name: Update Weather

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7,12,16 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
      - name: Update Weather
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          export BASE_FOLDER=$GITHUB_WORKSPACE 
          export SCRIPTS_FOLDER=${BASE_FOLDER}'/scripts'
          export SHELL_SCRIPT_NAME='update_github_readme'
          export PYTHON_SCRIPT='update_weather.py'
          python3 ${SCRIPTS_FOLDER}/${PYTHON_SCRIPT} --apikey "${APIKEY}"
          git config --global user.email "jackie.yt.wang@gmail.com"
          git config --global user.name "Jackie Wang"
          git add README.md
          git commit -m "Update weather"
          git push origin main





      
